Bugfixed tabulate for functions
git-svn-id: svn://127.0.0.1/pplsvn@414 8e462c0f-ee70-4953-a96e-5db927b55778

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -210,7 +210,31 @@ else
  exit
 fi
 
-# 14. OUTPUT MAKEFILE
+# 14. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBPNG HEADERS
+
+echo $ECHO_N "Checking for libpng-dev        ............. $ECHO_C"
+if printf '#include <stdlib.h>\n#include <stdio.h>\n#include <png.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
+then
+ echo "YES"
+else
+ echo "NO"
+ echo "ERROR: Header files for required library 'libpng' could not be found." >&2
+ exit
+fi
+
+# 15. CHECK TO SEE WHETHER THIS SYSTEM HAS KPATHSEA HEADERS
+
+echo $ECHO_N "Checking for libkpathsea-dev   ............. $ECHO_C"
+if printf '#include <stdlib.h>\n#include <stdio.h>\n#include <kpathsea/kpathsea.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
+then
+ echo "YES"
+else
+ echo "NO"
+ echo "ERROR: Header files for required library 'libkpathsea-dev' could not be found." >&2
+ exit
+fi
+
+# 16. OUTPUT MAKEFILE
 
 cat Makefile.skel >> Makefile
 
