First postscript. All output terminals now working.
git-svn-id: svn://127.0.0.1/pplsvn@457 8e462c0f-ee70-4953-a96e-5db927b55778

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -99,7 +99,19 @@ else
  echo "WARNING: wget could not be found. Installation will proceed, but PyXPlot will not be able to plot files directly from URLs." >&2
 fi
 
-# 7. FIND GHOSTVIEW
+# 7. CHECK FOR GHOSTSCRIPT
+
+echo $ECHO_N "Checking for ghostscript       ............. $ECHO_C"
+whichout=`which gs 2> /dev/null`
+if test "`echo $whichout | sed 's/\([a-z]*\).*/\1/'`" = "no" ; then whichout="" ; fi
+if test "$whichout" != "" ; then
+ echo "YES"
+ echo "GS_COMMAND=${whichout}" >> Makefile
+else
+ echo "NO" ; echo "ERROR: Required program ghostscript could not be found." >&2 ; exit
+fi
+
+# 8. FIND GHOSTVIEW
 
 echo $ECHO_N "Checking for ghostview         ............. $ECHO_C"
 whichout_gv=`which gv 2> /dev/null`
@@ -126,7 +138,7 @@ else
  echo "WARNING: Ghostview could not be found. Installation will proceed, but X11 terminal will not be available in PyXPlot. If required, install either ghostview (gv) or Gnome-ghostview (ggv), and then re-install PyXPlot." >&2
 fi
 
-# 8. FIND MAKE
+# 9. FIND MAKE
 
 echo $ECHO_N "Checking for GNU make          ............. $ECHO_C"
 whichout_make=`which make 2> /dev/null`
@@ -147,7 +159,7 @@ else
  exit
 fi
 
-# 9. CHECK TO SEE WHETHER THIS SYSTEM HAS GNU READLINE HEADERS
+# 10. CHECK TO SEE WHETHER THIS SYSTEM HAS GNU READLINE HEADERS
 
 echo $ECHO_N "Checking for libreadline-dev   ............. $ECHO_C"
 if printf '#include <readline/readline.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -159,7 +171,7 @@ else
  echo "HAVE_READLINE=-D NOHAVE_READLINE=1" >> Makefile
 fi
 
-# 10. CHECK TO SEE WHETHER THIS SYSTEM HAS CFITSIO HEADERS
+# 11. CHECK TO SEE WHETHER THIS SYSTEM HAS CFITSIO HEADERS
 
 echo $ECHO_N "Checking for libcfitsio-dev    ............. $ECHO_C"
 if printf '#include <fitsio.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -173,7 +185,7 @@ else
  echo "FITSIO_LINK=" >> Makefile
 fi
 
-# 11. CHECK TO SEE WHETHER THIS SYSTEM HAS GSL HEADERS
+# 12. CHECK TO SEE WHETHER THIS SYSTEM HAS GSL HEADERS
 
 echo $ECHO_N "Checking for libgsl0-dev       ............. $ECHO_C"
 if printf '#include <gsl/gsl_version.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -185,7 +197,7 @@ else
  exit
 fi
 
-# 12. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBXML2 HEADERS
+# 13. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBXML2 HEADERS
 
 echo $ECHO_N "Checking for libxml2-dev       ............. $ECHO_C"
 whichout=`which xml2-config 2> /dev/null`
@@ -198,7 +210,7 @@ else
  exit
 fi
 
-# 13. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBJPEG HEADERS
+# 14. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBJPEG HEADERS
 
 echo $ECHO_N "Checking for libjpeg-dev       ............. $ECHO_C"
 if printf '#include <stdlib.h>\n#include <stdio.h>\n#include <jpeglib.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -210,7 +222,7 @@ else
  exit
 fi
 
-# 14. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBPNG HEADERS
+# 15. CHECK TO SEE WHETHER THIS SYSTEM HAS LIBPNG HEADERS
 
 echo $ECHO_N "Checking for libpng-dev        ............. $ECHO_C"
 if printf '#include <stdlib.h>\n#include <stdio.h>\n#include <png.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -222,7 +234,7 @@ else
  exit
 fi
 
-# 15. CHECK TO SEE WHETHER THIS SYSTEM HAS KPATHSEA HEADERS
+# 16. CHECK TO SEE WHETHER THIS SYSTEM HAS KPATHSEA HEADERS
 
 echo $ECHO_N "Checking for libkpathsea-dev   ............. $ECHO_C"
 if printf '#include <stdlib.h>\n#include <stdio.h>\n#include <kpathsea/kpathsea.h>\nint main() { return 0; }\n' | gcc -x c - -o /dev/null > /dev/null 2> /dev/null
@@ -234,7 +246,7 @@ else
  exit
 fi
 
-# 16. OUTPUT MAKEFILE
+# 17. OUTPUT MAKEFILE
 
 cat Makefile.skel >> Makefile
 
